---
title: A Guide to Facebook Security
authors: Linda McCarthy, Keith Watson, Denise Weldon-Siviy
published_on: 2011
added_on: 2011-07-07
topics: Security
languages: en
blurb: |
  This online guide explains how you can protect your facebook account, avoid the scammers, use advanced security settings, recover a hacked Facebook account, and stop imposters.
license: Creative Commons Attribution-NoDerivs 3.0 Unported 
publisher: Facebook
---
