---
title: Basic Internet Security
authors: Adam Hyde, Jan Gerber, Dan Hassan, Erik Stein, Sacha van Geffen, Mart van Santen, Lonneke van der Velden, Emile den Tex and Douwe Schmidt
published_on: 2011
added_on: 2011-07-08
topics: Censorship, Cryptography, Hacktivism
languages: en
blurb: |
  How to protect yourself, your sources or your friends? What are safe routes to take? How do you secure after your personal data? This manual aims to address these issues to help you choose your own 'level' of safety.
publisher: FLOSS Manuals
---
